import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import matter from "gray-matter";
import MarkdownIt from "markdown-it";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const contentDir = path.join(repoRoot, "content");
const profilePath = path.join(contentDir, "profile.json");
const publicationsPath = path.join(contentDir, "publications.md");
const outputPath = path.join(repoRoot, "src", "content.generated.js");

const markdown = new MarkdownIt({
  html: true,
  linkify: true,
  typographer: false,
});

export async function buildContent() {
  const profile = JSON.parse(await fs.readFile(profilePath, "utf8"));
  const publications = matter(await fs.readFile(publicationsPath, "utf8")).content.trim();
  const files = await collectMarkdownFiles(contentDir);
  const documents = [];

  for (const file of files) {
    const parsed = matter(await fs.readFile(file, "utf8"));
    if (parsed.data.draft) continue;

    const document = createDocument(file, parsed, { profile, publications });
    documents.push(document);
  }

  documents.sort((left, right) => {
    const leftOrder = Number.isFinite(left.order) ? left.order : Number.MAX_SAFE_INTEGER;
    const rightOrder = Number.isFinite(right.order) ? right.order : Number.MAX_SAFE_INTEGER;
    return leftOrder - rightOrder || left.title.localeCompare(right.title);
  });

  const publicDocuments = documents.map(({ order, ...document }) => document);
  const output = [
    "/* Generated by scripts/build-content.mjs. Do not edit directly. */",
    `export const PROFILE = ${JSON.stringify(profile, null, 2)};`,
    "",
    `export const DOCUMENTS = ${JSON.stringify(publicDocuments, null, 2)};`,
    "",
  ].join("\n");

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await writeIfChanged(outputPath, output);
  return { profile, documents: publicDocuments, outputPath };
}

function createDocument(file, parsed, siteData) {
  const markdownBody = expandShortcodes(parsed.content.trim(), siteData);
  const html = renderHtml(markdown.render(markdownBody), parsed.data, siteData.profile);
  const slug = String(parsed.data.slug || deriveSlug(file));
  const title = String(parsed.data.title || slug);
  const date = parsed.data.date ? String(parsed.data.date) : "";
  const tags = Array.isArray(parsed.data.tags) ? parsed.data.tags.map(String) : [];
  const order = Number(parsed.data.order);

  return {
    slug,
    title,
    date,
    tags,
    content: textFromHtml(html),
    html,
    order,
  };
}

function renderHtml(html, data, profile) {
  if (data.layout !== "home") return html;

  const splitAt = html.search(/<h2\b/i);
  const introHtml = splitAt === -1 ? html.trim() : html.slice(0, splitAt).trim();
  const restHtml = splitAt === -1 ? "" : html.slice(splitAt).trim();

  return `
<section class="home-profile">
  <div class="profile-copy">
    ${profileLinks(profile)}
    ${introHtml}
  </div>
  <img class="profile-photo" src="${escapeAttribute(profile.profileImage || "./profile.png")}" alt="${escapeAttribute(profile.name)}">
</section>
${restHtml}`.trim();
}

function expandShortcodes(content, siteData) {
  return content.replaceAll("{{publications}}", siteData.publications);
}

function profileLinks(profile) {
  const links = [
    ["Email", `mailto:${profile.email}`],
    ["GitHub", profile.github],
    ["Google Scholar", profile.scholar],
  ];

  return `
<ul class="profile-links">
${links.map(([label, href]) => `  <li><a href="${escapeAttribute(href)}">${escapeHtml(label)}</a></li>`).join("\n")}
</ul>`.trim();
}

async function collectMarkdownFiles(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const absolutePath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...await collectMarkdownFiles(absolutePath));
    } else if (entry.isFile() && entry.name.endsWith(".md")) {
      files.push(absolutePath);
    }
  }

  return files;
}

function deriveSlug(file) {
  const relative = path.relative(contentDir, file).replace(/\.md$/u, "");
  return relative
    .replace(/^pages\/home$/u, "index")
    .replace(/^posts\//u, "")
    .split(path.sep)
    .join("/");
}

function textFromHtml(html) {
  return html
    .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/giu, " ")
    .replace(/<style\b[^<]*(?:(?!<\/style>)<[^<]*)*<\/style>/giu, " ")
    .replace(/<[^>]+>/gu, " ")
    .replace(/&nbsp;/gu, " ")
    .replace(/&amp;/gu, "&")
    .replace(/&quot;/gu, "\"")
    .replace(/&#039;/gu, "'")
    .replace(/\s+/gu, " ")
    .trim();
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function escapeAttribute(value) {
  return escapeHtml(value).replace(/`/g, "&#096;");
}

async function writeIfChanged(file, content) {
  try {
    const current = await fs.readFile(file, "utf8");
    if (current === content) return;
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }

  await fs.writeFile(file, content);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  buildContent()
    .then(({ documents }) => {
      console.log(`Generated ${documents.length} documents.`);
    })
    .catch((error) => {
      console.error(error);
      process.exitCode = 1;
    });
}
